test-copy-uproc-results-to-irods:
	python3 copy_uproc_results_to_iplant_imicrobe.py \
		--source-root /work/05066/imicrobe/iplantc.org/data/imicrobe/projects \
		--target-root /iplant/home/shared/imicrobe/projects \
		--file-limit 100

copy-uproc-results-to-irods:
	python3 copy_uproc_results_to_iplant_imicrobe.py \
		--source-root /work/05066/imicrobe/iplantc.org/data/imicrobe/projects \
		--target-root /iplant/home/shared/imicrobe/projects
